CarWithAKT/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CarWithAKT.Models
{
    public class Location
    {
        public int Id { set; get; }
        public string Name { set; get; }
        public string Adress { set; get; }
    }
}

CarWithAKT/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarWithAKT.Models;

namespace CarWithAKT.Controllers
{
    public class LocationsController : Controller
    {
        private CarWithAKTContext db = new CarWithAKTContext();

        // GET: Locations
        public ActionResult Index()
        {
            return View(db.Locations.ToList());
        }

        [Authorize(Roles = "admin")]
        public ActionResult AdminIndex()
        {
            return View(db.Locations.ToList());
        }

        // GET: Locations/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Adress")] Location location)
        {
            if (ModelState.IsValid)
            {
                if(db.Locations.Any(x=>x.Name.ToLower() == location.Name.ToLower()))
                {
                    return RedirectToAction("Index");
                }
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(location);
        }
        // GET: Firms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location loc = db.Locations.Find(id);
            if (loc == null)
            {
                return HttpNotFound();
            }
            return View(loc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Adress")] Location loc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loc);
        }


        // GET: Locations/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CarWithAKT/Views/Locations/AdminIndex.cshtml
@model IEnumerable<CarWithAKT.Models.Location>

@{
    ViewBag.Title = "AdminIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="pagetitle">
        <h2>Доступні салони:</h2>


        <form action="@Url.Action("Create","Locations")"  method="get"><button style="display:block;margin: 0 auto" class="mybutton">Добавить салон</button></form>

    </div>

    <table class="table mytable" style="margin-top:20px">
        <tr>
            <th>
                Назва салону
            </th>
            <th>
                Адреса
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adress)
                </td>
                <td>
                    @Html.ActionLink("Видалити", "Delete", new { id = item.Id }, new { @style = "text-decoration:none;color:black" })
                    <p style="width:30px"></p>
                    @Html.ActionLink("Змінити назву", "Edit", new { id = item.Id }, new { @style = "text-decoration:none;color:black" })
                </td>
            </tr>
        }

    </table>
    

</div>

CarWithAKT/Views/Locations/Create.cshtml
@model CarWithAKT.Models.Location

@{
    ViewBag.Title = "Новий салон";
    Layout = "~/Views/Shared/_Layout.cshtml";
}<div class="container">
    <div class="pagetitle">
        <h2>Новый салон</h2>
        <form action="@Url.Action("Index","Locations")"><button style="display:block;margin: 0 auto" class="mybutton">Вернутся к списку</button></form>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            <div class="form-group">
                
                <div class="col-md-10">
                    <p>Назва салону:</p>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
               
                <div class="col-md-10">
                    <p>Адреса:</p>
                    @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
                </div>
            </div>

            <button type="submit" value="Save" class="mybutton">Зберегти</button>
        </div>
    }


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    </div>

CarWithAKT/Views/Locations/Edit.cshtml
@model CarWithAKT.Models.Location

@{
    ViewBag.Title = "Редагування салона";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="pagetitle">
        <h2>Редагування салона</h2>
        <form action="@Url.Action("Index","Locations")"><button style="display:block;margin: 0 auto" class="mybutton">Вернутся к списку</button></form>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div style="display: flex; justify-content: center">
            <div class="form-horizontal" style="display: flex; flex-direction: column; justify-content: center; width: 600px; align-items: center">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group" style="display:flex;flex-direction:column;justify-content:center; width:500px;align-items:center">
                <p>Назва салона:</p>
                <div class="col-md-10" style="width:100%;display:flex;justify-content:center">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <p>Адрес салона:</p>
                <div class="col-md-10" style="width:100%;display:flex;justify-content:center">
                    @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
                </div>
            </div>

                <button type="submit" value="Save" class="mybutton">Зберегти</button>
            </div>
        </div>
    }
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

CarWithAKT/Views/Locations/Index.cshtml
@model IEnumerable<CarWithAKT.Models.Location>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container"">
    <div class="pagetitle" >
        <h2>Доступні салони:</h2>

        @if (User.IsInRole("admin"))
        {
            <form action="@Url.Action("AdminIndex","Locations")"><button style="display:block;width:170px;margin: 0 auto" class="mybutton">Администрирование</button></form>
        }

    </div>

    <div class="row mt-15 mb-2" style="margin-top:70px;">
        @for (int i = 0; i < Model.Count(); i++)
        {
        <div class="col-lg-6">
            <div class="mycircle">
                <p>@(i+1)</p>
            </div>
            <p class="circlename">@Model.ElementAt(i).Name</p>
            <p class="circleadress">@Model.ElementAt(i).Adress</p>
        </div>
        }
    </div>



</div>