CarWithAKT/Models/Firm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CarWithAKT.Models
{
    public class Firm
    {
        public int Id { get; set; }
        public string Name { set; get; }
    }
}

CarWithAKT/Controllers/FirmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarWithAKT.Models;

namespace CarWithAKT.Controllers
{
    public class FirmsController : Controller
    {
        private CarWithAKTContext db = new CarWithAKTContext();

        // GET: Firms
        public ActionResult Index()
        {
            return View(db.Firm.ToList());
        }

        // GET: Firms/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Firms/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Firm firm)
        {
            if (ModelState.IsValid)
            {
                if (db.Firm.Any(f => f.Name.ToLower() == firm.Name.ToLower()))
                {
                    return RedirectToAction("Index");
                }
                db.Firm.Add(firm);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(firm);
        }

        // GET: Firms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Firm firm = db.Firm.Find(id);
            if (firm == null)
            {
                return HttpNotFound();
            }
            return View(firm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Firm firm)
        {
            if (ModelState.IsValid)
            {
                db.Entry(firm).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(firm);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Firm firm = db.Firm.Find(id);
            if (firm == null)
            {
                return HttpNotFound();
            }
            db.Firm.Remove(firm);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CarWithAKT/Views/Firms/Create.cshtml
@model CarWithAKT.Models.Firm

@{
    ViewBag.Title = "Нова фірма";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="pagetitle">
        <h2>Новая фирма</h2>
        <form action="@Url.Action("Index","Firm")"><button style="display:block;margin: 0 auto" class="mybutton">Вернутся к списку</button></form>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
<div style="display: flex; justify-content: center">
    <div class="form-horizontal" style="display: flex; flex-direction: column; justify-content: center; width: 600px; align-items: center">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="display:flex;flex-direction:column;justify-content:center; width:500px;align-items:center">
            <p>Название фирмы-производителя:</p>
            <div class="col-md-10" style="width:100%;display:flex;justify-content:center">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <button type="submit" value="Save" class="mybutton">Зберегти</button>
    </div>
</div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    </div>

CarWithAKT/Views/Firms/Edit.cshtml
@model CarWithAKT.Models.Firm

@{
    ViewBag.Title = "Редагування фірми";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="pagetitle">
        <h2>Редактирование фирмы</h2>
        <form action="@Url.Action("Index","Firm")"><button style="display:block;margin: 0 auto" class="mybutton">Вернутся к списку</button></form>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div style="display: flex; justify-content: center">
            <div class="form-horizontal" style="display: flex; flex-direction: column; justify-content: center; width: 600px; align-items: center">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group" style="display:flex;flex-direction:column;justify-content:center; width:500px;align-items:center">
                    <p>Название фирмы-производителя:</p>
                    <div class="col-md-10" style="width:100%;display:flex;justify-content:center">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <button type="submit" value="Save" class="mybutton">Зберегти</button>
            </div>
        </div>
    }
        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
</div>

CarWithAKT/Views/Firms/Index.cshtml
@model IEnumerable<CarWithAKT.Models.Firm>

@{
    ViewBag.Title = "Фірми";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    @if (User.IsInRole("admin") || User.IsInRole("worker"))
    {
    <div class="pagetitle">
        <h2>Фірми</h2>


        <form action="@Url.Action("Create", "Firms")"><button style="display:block;margin: 0 auto" class="mybutton">Добавить фирму</button></form>
        

    </div>
        <p>

        </p>
        <table class="table">
            <tr>
                <th>
                    Назва фірми:
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td style="display:flex;flex-direction:row;justify-content:center;">
                        @if (User.IsInRole("admin"))
                        {
                            @Html.ActionLink("Видалити", "Delete", new { id = item.Id }, new {@style = "text-decoration:none;color:black" })
                            <p style="width:30px"></p>
                            @Html.ActionLink("Змінити название", "Edit", new { id = item.Id }, new { @style = "text-decoration:none;color:black" })
                        }
                    </td>
                </tr>
            }


        </table>
    }
    else
    {
        <div class="pagetitle">
            <h2>Фірми</h2>
        </div>
        <p>

        </p>
        <div style="display:flex;justify-content:center;">
            <table class="table" style="width:400px">
                <tr>
                    <th style="text-align: center;">
                        Назва фірми:
                    </th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style="text-align: center;">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                    </tr>
                }
            </table>
        </div>
            }
</div>